// <auto-generated />
using System;
using Assignment3.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Assignment3.Migrations
{
    [DbContext(typeof(LearningModel))]
    [Migration("20190911025820_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079");

            modelBuilder.Entity("Assignment3.Models.Course", b =>
                {
                    b.Property<int>("CourseId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("CourseNumber");

                    b.Property<string>("Department");

                    b.Property<string>("Description");

                    b.Property<string>("Name");

                    b.Property<string>("Semester");

                    b.Property<int>("Year");

                    b.HasKey("CourseId");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("Assignment3.Models.LearningOutcome", b =>
                {
                    b.Property<int>("LearningId")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("CourseId");

                    b.Property<int>("CourseInstanceId");

                    b.Property<string>("Description");

                    b.Property<string>("Name");

                    b.HasKey("LearningId");

                    b.HasIndex("CourseId");

                    b.ToTable("LearningOutcomes");
                });

            modelBuilder.Entity("Assignment3.Models.LearningOutcome", b =>
                {
                    b.HasOne("Assignment3.Models.Course")
                        .WithMany("LearningOutcomes")
                        .HasForeignKey("CourseId");
                });
#pragma warning restore 612, 618
        }
    }
}
